sprint 14: add-bookings
EvgeniyBudaev/java-shareit pull request #2
Opened 2023-01-27 06:01 UTC by EvgeniyBudaev

2023-01-27 23:11 UTC, AnastasiyaFomkina requested changes
Оставлю тут общие комментарии по работе: 

- Лучше стараться максимально декомпозировать большие методы на более мелкие логические состовляющие, так код будет проще читать и тестировать в дальнейшем

- Так как ты познакомился с транзакциями, хорошо было бы все сервисы сделать транзакционными
Для этого необходимо навесить над ними аннотацию
`@Transactional(readOnly = true)`, что указывает на то, что фиксация изменений не будет производиться) А над теми методами, где требуется фиксация в БД, необходимо использовать `@Transactional `

- Пакет `Exception` нужно переименовать в `exception`

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingDto addBooking(@RequestHeader("X-Sharer-User-Id") long userId,
У методов не хватает модификаторов доступа

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                      @RequestHeader("X-Sharer-User-Id") long userId) {
Повторяющиеся названия хэдеров лучше выносить в константы

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        Logger.logRequest(HttpMethod.PATCH, "/bookings/" + bookingId + "?approved=" + approved, "no body");
Для создания сложносоставного `url` лучше использовать [UriBuilder](https://docs.spring.io/spring-framework/docs/5.0.0.M4_to_5.0.0.M5/Spring%20Framework%205.0.0.M5/org/springframework/web/util/UriBuilder.html)

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingMapper.convertToDto(booking);
Лучше маппить на уровне сервиса, а не контроллера, так как маппинг - это тоже часть бизнес-логики программы.
Перенеси, пожалуйста, по всему проекту

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    private final ModelMapper modelMapper;
[Mapstruct](https://mapstruct.org/) сейчас более распространенная библиотека для маппинга сущностей. Она встречается почти в каждом проекте, так как ее очень удобно настраивать с помощью аннотаций, а еще она достаточно производительная.
Вот [тут](https://www.baeldung.com/java-performance-mapping-frameworks) можно посмотреть сравнения

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/model/StateEnumConverter.java
> +    public State convert(String source) {
Лучше перенести метод в `enum State` и сделать статическим, а этот класс удалить. 
Плюс метод `valueOf` два вида исключений: `IllegalArgumentException`, если не найден соответствующий элемент или `NullPointerException`, если элемент или название `null`, поэтому преобразовывать все ошибки к `IllegalArgumentException` не имеет смысла. 
Лучше создать свою ошибку и выбрасывать ее

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +public interface BookingService {
Молодец, что задокументировал методы 🔥

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookerId == item.getUserId()) {
Всю проверку (36 - 43) лучше вынести в отдельный метод, чтобы декомпозировать большой `addBooking`

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final CommentMapper commentMapper;
Лучше объединить методы репозиториев и мапперов в отдельный сервис и использовать его. Данный подход поможет сократить количество инжектов и декомпозировать большие методы. Например, если создать отдельный сервис для комментариев, то в нем можно создать метод, который будет искать комментарий по id и маппить его в нужную сущность, а уже здесь использовать полученный результат.

2023-01-27 23:11 UTC, afomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/share_it_db
Нужно использовать `postgresql` в данном задании

2023-01-27 23:11 UTC, afomkina commented on src/main/resources/schema.sql
> +    --owner_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
Лучше не комментировать, а удалять, если не нужно

2023-01-27 23:11 UTC, afomkina commented on src/main/resources/data.sql
> +delete from comments;
Если используется только для тестирования, то лучше удалить

2023-01-27 23:11 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        } catch (RuntimeException e) {
Лучше отлавливать какое-либо конкретное исключение или обрабатывать их в exception handler'е

2023-01-27 23:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    BookingMapper() {
Не хватает модификатора доступа на конструкторах в некоторых мапперах по проекту

2023-01-29 06:45 UTC, EvgeniyBudaev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final CommentMapper commentMapper;
" объединить методы репозиториев и мапперов в отдельный сервис и использовать его" - не понимаю, чем лучше? Мы наоборот декомпозировали по сервисам для удобства работы. Может я что-то пропустил, но в теории яндекс-практикума не было написано об этом архитектурном подходе. Можно ссылку на статью/пример реализации?

2023-01-30 08:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final CommentMapper commentMapper;
Это как раз про декомпозицию. По идее мы выносим в один класс всю логику взаимодействия с комментариями, что поможет сократить код методов и подключать одну зависимость вместо двух (маппера и репозитория). Получение из базы и маппинг считается бизнес-логикой, поэтому лучше выносить ее в отдельный сервис, так как она может дополниться еще какими-то шагами, например, если между получением и маппингом комментариев, нам придется делать с ними еще какие-либо действия. 

К сожалению, какой-либо статьи на этот счет скинуть не могу. Но [вот отличный сайт](https://refactoring.guru/ru/refactoring), где подробно описываются все code-smell, которые часто встречаются в проектах и пути их решения

Пока можно оставить, как есть, так как работа отличная. Если будет время можно полазить по разделу "Рефакторинг" и попробовать подекомпозировать большие методы сервиса к следующей работе

2023-01-30 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final CommentMapper commentMapper;
[Вот патч с примером](https://github.com/EvgeniyBudaev/java-shareit/files/10534292/Add_Comment_Service_Refactor_Item_Service_on_current_changes.patch), как можно с помощью объединения `CommentMapper` и `CommonRepository` в сервис, сократить методы ItemServiceImpl и сделать код чуть более читаемым.
Чтобы использовать патч, нужно закинуть файл в директорию проекта, нажать на нем правой кнопкой мыши и выбрать пункт `Apply Patch...`
<img width="464" alt="Снимок экрана 2023-01-30 в 12 32 35" src="https://user-images.githubusercontent.com/43168217/215439966-8c33939c-6678-4a5a-830c-3e0f69317bca.png">

Изменения можно будет посмотреть во вкладки с коммитом:
![Uploading Снимок экрана 2023-01-30 в 12.34.21.png…]()

2023-01-30 09:37 UTC, AnastasiyaFomkina approved these changes
Работу принимаю, в целом - все ок. Но лучше стараться максимально декомпозировать большие методы и выносить какие-то повторяющиеся элементы в отдельные методы или классы. К вопросу приложила патч с примером, если не получится применить и посмотреть - пиши в пачку, сделаем вместе :)

2023-01-30 16:09 UTC, merged